---
title: "PICs Analysis"
author: "Tim Farkas"
date: "9/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Libraries}
library(tidyverse)
library(GGally)
library(pls)
library(tidymodels)
```

```{r Load Data}

# all pics data
pd <- read_csv(file = "~/Dropbox/Projects/Sev/Plants/sev_traits_cv_manuscript/Data/all_pics_joined_1Jan2021.csv") %>%
  mutate_at(vars(node), function(x) as.character(as.numeric(word(x, 2, 2)))) %>%
  mutate(index = -1 * (a_p + cn + fr.diam + ldmc + lma + rdmc + sdmc + seed_mass)) %>%
  mutate(avc = a_p - cn )

pd_long <- pd %>%
  gather(key = "trait", value = "pic", a_p:d15N, fr.dens:index)

```




```{r Quick Regression Stats}
f.list <- names(pd)[c(2:3, 10, 25:30, 37, 45:49)]

# OLS linear regression
pees <- c(lapply(setNames(f.list, f.list), function(x) {
  
 summary(lm(F_F_BM_q1090 ~ pic, data=pd_long %>% filter(trait==x)))$coefficients[2, 4]
  
}), recursive=TRUE)

sigs <- ifelse(pees > 0.10, "", 
               ifelse(pees > 0.05, "#",
                      ifelse(pees > 0.01, "*", 
                             ifelse(pees > 0.001, "**", "***"))))

reg_out <- tibble(trait=names(pees), p=pees, sig=sigs)

# OLS quadratic regression
pees <- c(lapply(setNames(f.list, f.list), function(x) {
  
 summary(lm(F_F_BM_cv ~ pic + I(pic^2), data=pd_long %>% filter(trait==x)))$coefficients[3, 4]
  
}), recursive=TRUE)

sigs <- ifelse(pees > 0.10, "", 
               ifelse(pees > 0.05, "#",
                      ifelse(pees > 0.01, "*", 
                             ifelse(pees > 0.001, "**", "***"))))

reg_out <- tibble(trait=names(pees), p=pees, sig=sigs)
```

```{r LOESS plots against CV}
# all sites pairwise regression plots
a.list <- names(pd)[c(2:3, 10, 25:30, 37, 45:49)]

pd_long %>%  
  filter(trait %in% a.list) %>%
  ggplot(mapping=aes(y=F_A_BM_q1090, x=pic)) +
  geom_point() + 
  geom_smooth(method="lm") +
  facet_wrap(~ trait, scales="free")
  

# flats only pairwise regression plots
f.list <- names(pd)[c(2:3, 10, 25:30, 37, 45:49)]

pd_long %>%  
  filter(trait %in% f.list) %>%
  ggplot(mapping=aes(y=F_F_BM_q1090, x=pic)) +
  geom_point() + 
    facet_wrap(~ trait, scales="free") +
  geom_text(data = reg_out, 
              aes(x=Inf, y=Inf, label=reg_out$sig,
                  vjust=1, hjust=1),
              cex = 5, col="red") +
  geom_label(aes(label=node), cex=2) +
  geom_smooth(method="loess") 

ggsave(filename = "~/Dropbox/Projects/Sev/Plants/sev_traits_cv_manuscript/Figures/loess_reg_flats_q1090m.pdf", 
         device="pdf", height = 14, width=14)

```

```{r cv vs q1090}
pd %>% 
  ggplot(mapping=aes(x = F_F_BM_cv, y = F_F_BM_q1090)) +
  geom_point() + 
  geom_smooth(method = "loess")

ggsave(filename = "~/Dropbox/Projects/Sev/Plants/sev_traits_cv_manuscript/Figures/cv_vs_q1090m.pdf")
```


```{r Explore Data}
pd %>%
  select(F_A_BM_cv, 
         a_p, p95.height_A:d15N, cn, fr.dmc, ldmc, lma, rdmc, sdmc, seed_mass) %>%
ggpairs()

complete_pd <- pd %>%
  select(F_A_BM_cv, 
         a_p, area, p95.height_A, cn, fr.dens:lma, 
         rdens:seed_mass) %>%
  filter(complete.cases(.))

```

```{r Partial Least Squares}
pd_cull <- pd %>%
  select(F_A_BM_cv, a_p, area, cn, fr.dens:lma,  p95.height_A, rdens:seed_mass) %>%
  #transmute_all(.funs=function(x) scale(x)) %>%
  filter(complete.cases(.))

pls_fit <- plsr(F_A_BM_cv ~ ., data=pd_cull, validation="CV")

cv = RMSEP(pls_fit)
best.dims = which.min(cv$val[estimate = "adjCV", , ]) - 1

pls_fit <- plsr(F_A_BM_cv ~ ., data=pd_cull)

summary(lm(pd_cull$F_A_BM_cv ~ pls_fit$scores[,1] + pls_fit$scores[,2] + pls_fit$scores[,5]))

lapply(1:ncol(pls_fit$scores), function(x) summary(lm(pd_cull$F_A_BM_cv ~ pls_fit$scores[,x]))$coefficients[2,4])
pls_fit$loadings
pd_cull <- pd_cull %>%
  bind_cols(pls_fit$scores)
ggplot() +
  
```

```{r PCA}
pd_pca <- complete_pd %>%
  select(-F_A_BM_cv) %>%
  as.matrix() %>%
  prcomp(scale=TRUE)

plot(summary(pd_pca)$importance[3,],
     ylab="cumulative variance explained",
     xlab="PC Index")

# analysis 

pd_pca_2 <- complete_pd %>% 
  select(cv=F_A_BM_cv) %>%
  bind_cols(pd_pca$x %>%
  as_tibble()) 

pd_pca_2 %>% 
  select(cv:PC4) %>%
  # filter(between(cv, -1.5, 2)) %>%
  ggpairs()

# plot PCA space and color points by CV
pd_pca_2 %>%
  ggplot(aes(x=PC1, y=PC2)) + 
  geom_point(aes(color=cv))

pd_pca_2 %>%
  filter(between(cv, -1.5, 2)) %>%
  lm(cv ~ PC1 + PC2, data=.) %>%
  summary()

pd_pca$rotation


```

```{r NMDS}
library(MASS)

d <- pd %>% select(-F_A_BM_cv) %>%
  as.data.frame() %>%
  dist()

fit <- cmdscale(d, k=2)
nm_fit <- MASS::isoMDS(d, k=2)

as_tibble(nm_fit$points) %>%
  bind_cols(pd %>% select(F_A_BM_cv)) %>%
  select(dim1=V1, dim2=V2, CV=F_A_BM_cv) %>%
  
ggplot(aes(x=dim1, y=dim2, color=CV)) + 
  geom_point()
  





```
Tidymodels
```{r}
norm_rec <- 
  pd %>%
  select(a_p, area, cn, F_F_BM_cv, fr.srl, fr.diam, ldmc, lma,
         p95.height_F, rdens, sdmc, seed_mass) %>%
  recipe(F_F_BM_cv ~ ., data = .) %>%
  step_normalize(everything())

pls.model <- 
  pd %>%
  select(a_p, area, cn, F_F_BM_cv, fr.srl, fr.diam, ldmc, lma,
         p95.height_F, rdens, sdmc, seed_mass) %>%
  plsr(F_F_BM_cv ~ ., data = ., validation = "CV")
  
cv = RMSEP(pls.model)
best.dims = which.min(cv$val[estimate = "adjCV", , ]) - 1

pls.model <- 
  pd %>%r
  select(a_p, area, cn, F_F_BM_cv, fr.srl, fr.diam, ldmc, lma,
         p95.height_F, rdens, sdmc, seed_mass) %>%
  plsr(F_F_BM_cv ~ ., data = ., ncomp = best.dims)

coefficients = coef(pls.model)
sum.coef = sum(sapply(coefficients, abs))
coefficients = coefficients * 100 / sum.coef
coefficients = sort(coefficients[, 1 , 1])
barplot(tail(coefficients, 5))

summary(pls.model)

fit <- pls.model$fitted.values 
truth <- pd %>%
  select(a_p, area, cn, F_F_BM_cv, fr.srl, fr.diam, ldmc, lma,
         p95.height_F, rdens, sdmc, seed_mass) %>% 
   pull(F_F_BM_cv)

summary(lm(pd$F_F_BM_cv[pd$F_F_BM_cv <2] ~ preds[preds < 1]))

summary(pls.model)

## principal components regression
train <- sample(1:55, replace=FALSE, size = 40)
pcr.train <- 
  pd %>%
  select(a_p, area, cn, F_F_BM_cv, fr.srl, fr.diam, ldmc, lma,
         p95.height_F, rdens, sdmc, seed_mass) %>%
  drop_na() %>%
  slice(train)
pcr.test <- 
  pd %>%
  select(a_p, area, cn, F_F_BM_cv, fr.srl, fr.diam, ldmc, lma,
         p95.height_F, rdens, sdmc, seed_mass) %>%
  drop_na() %>%
  slice(-train)

pcr.model <- plsr(F_F_BM_cv ~ ., data = pcr.train, validation = "LOO")

predict(pcr.model, newdata = pcr.test)

predplot(pcr.model, newdata = pcr.test)
  
```

```{r ranger}
rf.data <- pd %>%
  select(a_p, area, cn, F_F_BM_cv, fr.srl, fr.diam, ldmc, lma,
         p95.height_F, rdens, sdmc, seed_mass) %>%
  drop_na() 


rf.mod <- train(y = rf.data$F_F_BM_cv, x = rf.data %>% 
        select(-F_F_BM_cv), 
      method = "gbm")

rf.mod
```



